version: '3'
services:
    dashboard:
        build: .
        restart: on-failure
        depends_on:
            - mysql-db
        ports:
            - 8080:8080
        environment:
            - DASHBOARD_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/dashboard
            - DASHBOARD_DATASOURCE_USERNAME=admin
            - DASHBOARD_DATASOURCE_PASSWORD=admin
    mysql-db:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=dashboard
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        ports:
            - 3306:3306
