name: automatization

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  Continuos-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Prepare Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: mvn test

  Continuos-Delivery:
    needs: Continuos-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to the development environment
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DASHBOARD_DEVELOPMENT }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
    if: ${{ github.event_name == 'pull_request' }}

  Continuos-Deployment:
    needs: Continuos-Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to the production environment
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DASHBOARD_PRODUCTION }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
    if: ${{ github.event_name == 'push' }}
